apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.deployment.name }}-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Values.servicemonitor.release }}  # must match kube-prometheus-stack's expected label
spec:
  selector:
    matchLabels:
      app: {{ .Values.service.appLabel }}
  endpoints:
    - port: {{ .Values.servicemonitor.port}}
      path: {{ .Values.servicemonitor.path }}
      interval: {{ .Values.servicemonitor.interval }}