apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskly-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring   # must match kube-prometheus-stack's expected label
spec:
  selector:
    matchLabels:
      app: taskly-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s