apiVersion: v1
kind: Service
metadata:
  name: taskly-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: taskly-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: taskly-api
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}