image:
  tag: "9741a4cc759d83e4eccb1c74adcbb88d7e8b901a"

replicaCount: 2

autoscaling:
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  hosts: 
    - alex.staging.taskly.ironlabs.online

extraEnv:
  TASKS_TABLE_NAME: tasks_staging