image:
  tag: "a4c7f9df588a689aa11b0710157951af460c062b"

replicaCount: 2

autoscaling:
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  hosts: 
    - alex.staging.taskly.ironlabs.online

extraEnv:
  TASKS_TABLE_NAME: tasks_staging