image:
  tag: "12a9ed1b1c3cb4d1c8844fd3f12135390f80459a"

replicaCount: 3

autoscaling:
  minReplicas: 3
  maxReplicas: 10

ingress:
  enabled: true
  hosts: 
    - alex.taskly.ironlabs.online
extraEnv:
  TASKS_TABLE_NAME: tasks_production