image:
  tag: "19d65a0c8f4db23890d9495201fee252917b24c5"

replicaCount: 2

autoscaling:
  minReplicas: 2
  maxReplicas: 5

ingress:
  enabled: true
  hosts: 
    - alex.staging.taskly.ironlabs.online

extraEnv:
  TASKS_TABLE_NAME: tasks_staging